### ISSUE TITLE
Incorrect amount of money is withdrawn from buyer's wallet and incorrect funds were sent to seller's wallet

### ISSUE THREAD

**Issue by kay4444** [splytcore/SplytProtocol#1] opened 2018-05-15 21:13 UTC
Please see "splytprotocol/test/AssetTest.js" TCs from "testing" branch. Take a look at the TCs:
1) "proper amount of money was withdrawn from buyer's account after contributing into NOT fractional asset."
2) "seller gets full cost of NOT fractional asset ."

**Comment by dipenjoshi** [comment] 2018-05-17 02:10
@kay4444 close this issue if you think it works as intended. thank you.

**Comment by dipenjoshi** [comment] 2019-11-08 05:52
fixed

**Closed** 2019-11-08 05:52 UTC
Labels: bug
